# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = golden_angle.o
LINKOBJ  = golden_angle.o
LIBS     = -L"C:/devc/DevCppPortable/MinGW64/lib" -L"C:/devc/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/devc/DevCppPortable/MinGW64/include" -I"C:/devc/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/devc/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/devc/DevCppPortable/MinGW64/include" -I"C:/devc/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/devc/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/devc/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = flow_ctrol.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

golden_angle.o: golden_angle.c
	$(CPP) -c golden_angle.c -o golden_angle.o $(CXXFLAGS)
