# Project: Project4
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = contact_judge.o
LINKOBJ  = contact_judge.o
LIBS     = -L"D:/OneDrive/Tools/DevCppPortable/MinGW64/lib" -L"D:/OneDrive/Tools/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/OneDrive/Tools/DevCppPortable/MinGW64/include" -I"D:/OneDrive/Tools/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/OneDrive/Tools/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/OneDrive/Tools/DevCppPortable/MinGW64/include" -I"D:/OneDrive/Tools/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/OneDrive/Tools/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/OneDrive/Tools/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = pointer.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

contact_judge.o: contact_judge.c
	$(CC) -c contact_judge.c -o contact_judge.o $(CFLAGS)
